name: Build Godot Project for Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: main

    - name: Setup Godot
      uses: lihop/setup-godot@v2
      with:
        version: 4.2.1-stable
        bits: 64
        mono: true
        alias: godot
        export-templates: true
      
    - name: Install dotnet
      run: sudo apt install -y mono-devel
  
    - name: Verify
      run: |
        v4.2.1-stable/Godot_v4.2.1-stable_mono_linux_x86_64/Godot_v4.2.1-stable_mono_linux.x86_64 --version
    - name: Build project
      run: |
        tree
    - name: Export project
      run: |
        zip v4.2.1-stable
