name: Build Godot Project for Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Godot for Windows
      run: |
        Invoke-WebRequest -Uri "https://downloads.tuxfamily.org/godotengine/4.2.1/mono/Godot_v4.2.1-stable_mono_win64.zip" -OutFile "Godot_v4.2.1-stable_mono_win64.exe"
        echo "GODOT_PATH=$(pwd)/Godot_v4.2.1-stable_mono_win64.exe" >> $env:GITHUB_ENV

    - name: Build with Godot for Windows
      run: |
        & $env:GODOT_PATH --export-pack "Windows Desktop" "Fight-Jump.exe"
