name: Build Godot Project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Godot
      uses: Vitorgus/Setup-Godot@v1.1.1
      with:
        godot-version: 4.2.1
        download-mono: true

    - name: Build with Godot
      run: |
        godot --export-release "windows" ./Fight-Jump.exe
