name: Build Godot Project for Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Godot for Windows
      run: |
        wget https://downloads.tuxfamily.org/godotengine/4.2.1/mono/Godot_v4.2.1-stable_mono_linux_x86_64.zip
        echo "GODOT_PATH=$(pwd)/Godot_v4.2.1-stable_mono_linux_x86_64.zip" >> $GITHUB_ENV

    - name: Set executable permissions
      run: sudo chmod +x ${{ env.GODOT_PATH }}


    - name: Build with Godot for Windows
      run: |
        $GODOT_PATH --export-release "windows" ./Fight-Jump.exe
