name: Build Godot Project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Godot
      uses: lihop/godot-setup@v2.1.3
      with:
        version: 4.2.1-stable
        mono: true

    - name: Get tree
      run: | 
        tree

    - name: Build with Godot
      run: |
        godot --export-release "windows" ./Fight-Jump.exe
