name: Build Godot Project for Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Godot for Windows
      run: |
        wget https://downloads.tuxfamily.org/godotengine/4.2.1/mono/Godot_v4.2.1-stable_mono_linux_x86_64.zip
        unzip Godot_v4.2.1-stable_mono_linux_x86_64.zip
        echo "GODOT_PATH=$(pwd)/Godot_v4.2.1-stable_mono_linux_x86_64/Godot_v4.2.1-stable_mono_linux.x86_64" >> $GITHUB_ENV
        # Скачиваем архив с шаблонами экспорта для Windows
        sudo mkdir -p /github/home/.local/share/godot/export_templates/
        wget https://downloads.tuxfamily.org/godotengine/4.2.1/Godot_v4.2.1-stable_export_templates.tpz
        sudo unzip Godot_v4.2.1-stable_export_templates.tpz -d /github/home/.local/share/godot/export_templates/
        tree
        
    - name: Install dotnet
      run: sudo apt install -y mono-devel
  
    - name: Set executable permissions
      run: sudo chmod +x ${{ env.GODOT_PATH }}

    - name: Build with Godot Mono Build Action
      uses: QuakeEye/godot-mono-build-action@v0.0.2
      with:
        name: Jump-Fight
        preset: windows
        debugMode: true
        subdirectory: build

   
    - name: Get tree
      run : tree
    
